server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: demo
  profiles:
    active: @profileActive@
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: ["/templates/","/resources/","/static/","/public/"]
  mvc:
    static-path-pattern: /static/**
  messages:
    basename: message/app
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    # 开发阶段务必关闭缓存 (=false)
    cache: false
    servlet:
      content-type: text/html
# mybatis-plus配置
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  global-config:
    db-config:
      id-type: id_worker